language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - set -o pipefail
  - curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
  - chmod +x tr-reporter

  - go get github.com/jstemmer/go-junit-report
  - go test -count=1 -v 2>&1 ./... | tee /dev/tty | go-junit-report | ./tr-reporter
